package ayala.tidytivi.companion;
import android.app.*;import android.os.*;import android.widget.*;import android.database.*;import android.database.sqlite.*;import org.json.*;import java.io.*;
public class MergeTestActivity extends Activity {
 void check(boolean value,String msg)throws Exception{if(!value)throw new Exception(msg);}
 long value(File file,String query){SQLiteDatabase d=SQLiteDatabase.openDatabase(file.getPath(),null,SQLiteDatabase.OPEN_READONLY);try(Cursor c=d.rawQuery(query,null)){c.moveToFirst();return c.getLong(0);}finally{d.close();}}
 void sql(File file,String...queries){SQLiteDatabase d=SQLiteDatabase.openDatabase(file.getPath(),null,SQLiteDatabase.OPEN_READWRITE);for(String q:queries)d.execSQL(q);d.close();}
 void asset(String name,File f)throws Exception{try(InputStream i=getAssets().open(name);OutputStream o=new FileOutputStream(f)){byte[] b=new byte[65536];int n;while((n=i.read(b))!=-1)o.write(b,0,n);}}
 JSONObject manifest(long id,String key,String name)throws Exception{return new JSONObject().put("group_mappings",new JSONArray().put(new JSONObject().put("playlist","lineup-1.m3u").put("id",id).put("key",key).put("name",name)));}
 public void onCreate(Bundle b){super.onCreate(b);TextView text=new TextView(this);setContentView(text);new Handler().postDelayed(()->{for(java.util.Map.Entry<Thread,StackTraceElement[]> entry:Thread.getAllStackTraces().entrySet()){boolean merger=false;for(StackTraceElement frame:entry.getValue())if(frame.getClassName().contains("CurationMerge")||frame.getClassName().contains("VodMerge"))merger=true;if(merger)for(StackTraceElement frame:entry.getValue())android.util.Log.i("MergeRegression","WAIT "+frame.toString());}},10000);new Thread(()->{String result;try{
 File r=new File(getFilesDir(),"receiver.db"),i=new File(getFilesDir(),"incoming.db");asset("receiver.db",r);asset("incoming.db",i);
 JSONObject old=manifest(1,"1:1","Local"),incoming=manifest(1,"1:1","US: Local");
 CurationMerge.merge(r,i,old,incoming);check(value(r,"SELECT is_favorite FROM channels WHERE id=1")==1,"favorite");check(value(r,"SELECT is_visible FROM channel_group_options WHERE group_id=1")==0,"hidden group");check(value(r,"SELECT is_enabled FROM playlists WHERE id=1")==0,"hidden playlist");check(value(r,"SELECT last_played_position_ms FROM movies WHERE id=1")==10000,"movie progress");
 CurationMerge.merge(r,i,incoming,new JSONObject(incoming.toString()));check(value(r,"SELECT count(*) FROM channel_groups")==1,"repeat duplicates");
 sql(i,"UPDATE channel_groups SET name='Completely different' WHERE id=1");JSONObject rename=manifest(1,"1:1","Completely different");CurationMerge.merge(r,i,incoming,rename);check(value(r,"SELECT id FROM channel_groups WHERE name='Completely different'")==1,"rename ID");check(value(r,"SELECT is_visible FROM channel_group_options WHERE group_id=1")==0,"rename hidden");
 JSONObject replacement=manifest(1,"1:2","Completely different");CurationMerge.merge(r,i,rename,replacement);check(value(r,"SELECT count(*) FROM channel_groups")==2,"new identity should create group");check(value(r,"SELECT deleted_time IS NOT NULL FROM channel_groups WHERE id=1")==1,"obsolete group retired");check(value(r,"SELECT count(*) FROM channel_group_links WHERE group_id=1")==0,"stale membership removed");
 JSONObject returned=manifest(1,"1:1","Completely different");CurationMerge.merge(r,i,replacement,returned);check(value(r,"SELECT original_group_id FROM channels WHERE id=1")==1,"returned category identity");check(value(r,"SELECT deleted_time IS NULL FROM channel_groups WHERE id=1")==1,"returned category restored");check(value(r,"SELECT is_visible FROM channel_group_options WHERE group_id=1")==0,"returned group hidden");check(value(r,"SELECT is_favorite FROM channels WHERE id=1")==1,"favorite after repeat");
 SQLiteDatabase source=SQLiteDatabase.openDatabase(i.getPath(),null,SQLiteDatabase.OPEN_READWRITE);StringBuilder cols=new StringBuilder();try(Cursor c=source.rawQuery("PRAGMA table_info(playlists)",null)){while(c.moveToNext()){String name=c.getString(1);if(name.equals("id"))continue;if(cols.length()>0)cols.append(',');cols.append(name);}}source.execSQL("INSERT INTO playlists ("+cols+") SELECT "+cols+" FROM playlists WHERE id=1");source.execSQL("UPDATE playlists SET include_vod=1,url='xc:different-test-account' WHERE id=(SELECT max(id) FROM playlists)");source.close();
 boolean refused=false;try{CurationMerge.merge(r,i,returned,manifest(1,"1:1","Completely different"));}catch(IOException expected){refused=expected.getMessage().contains("provider cannot be matched");}check(refused,"different account rejected");check(value(r,"SELECT is_favorite FROM channels WHERE id=1")==1,"account rejection preserved favorite");
 sql(r,"INSERT INTO playlists ("+cols+") SELECT "+cols+" FROM playlists WHERE id=1","UPDATE playlists SET include_vod=1,url='xc:old-account' WHERE id=2","UPDATE movies SET playlist_id=2,xc_id=11,url='old-url' WHERE id=1","INSERT INTO movies (playlist_id,xc_id,name,display_mode,is_favorite,last_played_position_ms) VALUES (2,13,'Unavailable',0,1,9000)","INSERT INTO movie_categories (playlist_id,xc_id,name,is_visible) VALUES (2,101,'Movies',0)","UPDATE movies SET category_id=1 WHERE id=1","INSERT INTO series (playlist_id,xc_id,name,display_mode,is_favorite,last_episode_xc_id) VALUES (2,21,'Series',0,1,201)","INSERT INTO episode_last_played_positions (series_id,episode_xc_id,position_ms,duration_ms) VALUES (1,201,8000,40000)");
 sql(i,"UPDATE movies SET playlist_id=2,xc_id=11,url='new-url' WHERE id=1","INSERT INTO movies (playlist_id,xc_id,name,display_mode,is_favorite,last_played_position_ms) VALUES (2,12,'New movie',0,0,0)","INSERT INTO movie_categories (playlist_id,xc_id,name,is_visible) VALUES (2,101,'Movies renamed',1)","UPDATE movies SET category_id=1 WHERE id=1","INSERT INTO series (playlist_id,xc_id,name,display_mode,is_favorite,last_episode_xc_id) VALUES (2,21,'Series new name',0,0,0)");
 CurationMerge.merge(r,i,returned,manifest(1,"1:1","Completely different"));
 check(value(r,"SELECT url='xc:different-test-account' FROM playlists WHERE id=2")==1,"export account applied");check(value(r,"SELECT url='new-url' FROM movies WHERE id=1")==1,"movie credentials applied");check(value(r,"SELECT last_played_position_ms FROM movies WHERE id=1")==10000,"movie resume across accounts");check(value(r,"SELECT is_favorite FROM movies WHERE id=1")==1,"movie favorite across accounts");check(value(r,"SELECT deleted_time IS NOT NULL FROM movies WHERE xc_id=13")==1,"unavailable title retired");check(value(r,"SELECT last_played_position_ms FROM movies WHERE xc_id=13")==9000,"unavailable history retained");check(value(r,"SELECT count(*) FROM movies WHERE xc_id=12")==1,"new movie imported");check(value(r,"SELECT is_visible FROM movie_categories WHERE id=1")==0,"hidden VOD category retained");check(value(r,"SELECT last_episode_xc_id FROM series WHERE id=1")==201,"series progress retained");check(value(r,"SELECT position_ms FROM episode_last_played_positions WHERE series_id=1")==8000,"episode resume retained");
 sql(i,"INSERT INTO playlists ("+cols+") SELECT "+cols+" FROM playlists WHERE id=1","UPDATE playlists SET name='New profile',include_vod=0,url='file:///sdcard/Download/tidyTIVI/current/lineup-2.m3u' WHERE id=3");
 CurationMerge.merge(r,i,returned,manifest(1,"1:1","Completely different"));CurationMerge.merge(r,i,returned,manifest(1,"1:1","Completely different"));
 check(value(r,"SELECT count(*) FROM playlists WHERE url='file:///sdcard/Download/tidyTIVI/current/lineup-2.m3u'")==1,"new profile only once");check(value(r,"SELECT is_favorite FROM channels WHERE id=1")==1,"existing profile favorite after new profile");
 result="PASS: repeat/category identity, favorites, hidden settings, provider matching, exported account migration, movie and episode progress, unavailable history, new VOD";
 }catch(Exception e){result="FAIL: "+e.toString();}final String message=result;android.util.Log.i("MergeRegression",getIntent().getStringExtra("run_id")+" "+result);runOnUiThread(()->text.setText(message));}).start();}
}